"""create admission_requests table

Revision ID: 3766cd42102f
Revises: 
Create Date: 2026-04-13 10:25:56.352668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3766cd42102f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_requests',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('mother_tongue', sa.String(length=50), nullable=True),
    sa.Column('grade_applying_for', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('contact_phone', sa.String(length=15), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('residential_address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('primary_guardian', sa.JSON(), nullable=False),
    sa.Column('secondary_guardian', sa.JSON(), nullable=True),
    sa.Column('previous_school', sa.JSON(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('special_needs', sa.Text(), nullable=True),
    sa.Column('how_did_you_hear', sa.String(length=200), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('data_privacy_accepted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admission_requests')
    # ### end Alembic commands ###
